; For 1.2


[Constants]
global $Shadow = 0

[KeyShadow]
key = page_up
type = cycle
$Shadow = 0,1


; Overrides ---------------------------

[ShaderOverrideShadow1]
hash = d7bb9dd57f5b70c6
allow_duplicate_hash = true
run = CommandListShadowShader

; CommandList -------------------------

[CommandListShadowShader]
if $Shadow == 1
	handling = skip
endif