; For 1.2


[Constants]
global $Foliage = 0

[KeyFoliage]
key = end
type = cycle
$Foliage = 0,1


; Overrides ---------------------------

[ShaderOverrideFoliage1]
hash = 2b25f946bef3991b
allow_duplicate_hash = true
run = CommandListFoliageShader

[ShaderOverrideFoliage2]
hash = ef30a3ac561fcdb6
allow_duplicate_hash = true
run = CommandListFoliageShader

[ShaderOverrideFoliage3]
hash = 07f12d44af53b55c
allow_duplicate_hash = true
run = CommandListFoliageShader

[ShaderOverrideFoliage4]
hash = 40a51fe5c38738a8
allow_duplicate_hash = true
run = CommandListFoliageShader

[ShaderOverrideFoliage5]
hash = 62984fcafae5733a
allow_duplicate_hash = true
run = CommandListFoliageShader

[ShaderOverrideFoliage6]
hash = 28833dff69d052a7
allow_duplicate_hash = true
run = CommandListFoliageShader

; CommandList -------------------------

[CommandListFoliageShader]
if $Foliage == 1
	handling = skip
endif
